name: Build Firmware
on:
  workflow_dispatch:
  push:

jobs:
  load_conf:
    runs-on: ubuntu-22.04
    outputs:
      refs: ${{ steps.load_step.outputs.refs }}
      standalones: ${{ steps.load_step.outputs.standalones }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: load_step
        name: Load Config
        run: | 
          python loadConf.py
          cat $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-22.04
    needs:
      - load_conf
    strategy:
      matrix:
        ref: ${{ fromJSON(needs.load_conf.outputs.refs) }}
        standalone: ${{ fromJson(needs.load_conf.outputs.standalones) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          # Install dependencies
          # use `apt-get` rather than `apt` there. The former is for scripts and the latter is for terminal
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends git ca-certificates build-essential \
            pkg-config libreadline-dev gcc-arm-none-eabi libnewlib-dev libbz2-dev libssl-dev

      - name: Build
        env:
          MATRIX_REF: ${{ matrix.ref }}
          MATRIX_STANDALONE: ${{ matrix.standalone }}
        run: |
          python build.py

      - name: Show checksum
        run: |
          python checksum.py

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware_${{ matrix.ref }}_${{ matrix.standalone }}
          path: |
            artifacts/**/*.elf
            artifacts/**/*.s19
            artifacts/**/*.txt
            artifacts/**/Makefile.platform

